//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotoTools.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RotoTools.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizador.
        /// </summary>
        internal static string L_Actualizador {
            get {
                return ResourceManager.GetString("L_Actualizador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Quieres aplicar una traducción?.
        /// </summary>
        internal static string L_AplicarPlantillaTraduccion {
            get {
                return ResourceManager.GetString("L_AplicarPlantillaTraduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string L_Buscar {
            get {
                return ResourceManager.GetString("L_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conector de herraje.
        /// </summary>
        internal static string L_ConectorHerraje {
            get {
                return ResourceManager.GetString("L_ConectorHerraje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración restaurada correctamente..
        /// </summary>
        internal static string L_ConfiguracionRestaurada {
            get {
                return ResourceManager.GetString("L_ConfiguracionRestaurada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurador de opciones.
        /// </summary>
        internal static string L_ConfiguradorOpciones {
            get {
                return ResourceManager.GetString("L_ConfiguradorOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar y guardar opciones.
        /// </summary>
        internal static string L_ConfigurarGuardarOpciones {
            get {
                return ResourceManager.GetString("L_ConfigurarGuardarOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configurar opciones.
        /// </summary>
        internal static string L_ConfigurarOpciones {
            get {
                return ResourceManager.GetString("L_ConfigurarOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al instalar se perderán los datos actuales de los escandallos seleccionados. ¿Desea continuar?.
        /// </summary>
        internal static string L_ConfirmarInstalar {
            get {
                return ResourceManager.GetString("L_ConfirmarInstalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración Manillas FKS.
        /// </summary>
        internal static string L_ConfManillasFKS {
            get {
                return ResourceManager.GetString("L_ConfManillasFKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Constructivos aluminio.
        /// </summary>
        internal static string L_ConstructivosALU {
            get {
                return ResourceManager.GetString("L_ConstructivosALU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Constructivos PVC.
        /// </summary>
        internal static string L_ConstructivosPVC {
            get {
                return ResourceManager.GetString("L_ConstructivosPVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control de cambios.
        /// </summary>
        internal static string L_ControlCambios {
            get {
                return ResourceManager.GetString("L_ControlCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripciones Materiales Base.
        /// </summary>
        internal static string L_DescripcionesMB {
            get {
                return ResourceManager.GetString("L_DescripcionesMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elegir Scripts.
        /// </summary>
        internal static string L_EjecutarCarpeta {
            get {
                return ResourceManager.GetString("L_EjecutarCarpeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejecutar Scripts.
        /// </summary>
        internal static string L_EjecutarSQL {
            get {
                return ResourceManager.GetString("L_EjecutarSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error guardando archivo de configuración..
        /// </summary>
        internal static string L_ErrorGuardarConfiguracion {
            get {
                return ResourceManager.GetString("L_ErrorGuardarConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error restaurando archivo de configuración..
        /// </summary>
        internal static string L_ErrorRestaurandoConfiguracion {
            get {
                return ResourceManager.GetString("L_ErrorRestaurandoConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escandallos.
        /// </summary>
        internal static string L_Escandallos {
            get {
                return ResourceManager.GetString("L_Escandallos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escandallos instalados.
        /// </summary>
        internal static string L_EscandallosInstalados {
            get {
                return ResourceManager.GetString("L_EscandallosInstalados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un proveedor de Roto. ¿Desea agregar igualmente el proveedor Roto Frank SA?.
        /// </summary>
        internal static string L_ExisteProveedor {
            get {
                return ResourceManager.GetString("L_ExisteProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar datos.
        /// </summary>
        internal static string L_ExportarDatos {
            get {
                return ResourceManager.GetString("L_ExportarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar Escandallos.
        /// </summary>
        internal static string L_ExportarEscandallos {
            get {
                return ResourceManager.GetString("L_ExportarEscandallos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión bombillos.
        /// </summary>
        internal static string L_GestionBombillos {
            get {
                return ResourceManager.GetString("L_GestionBombillos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión general.
        /// </summary>
        internal static string L_GestionGeneral {
            get {
                return ResourceManager.GetString("L_GestionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión manillas.
        /// </summary>
        internal static string L_GestionManillas {
            get {
                return ResourceManager.GetString("L_GestionManillas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos presupuestado, producción y proveedor.
        /// </summary>
        internal static string L_GroupsSupplier {
            get {
                return ResourceManager.GetString("L_GroupsSupplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos.
        /// </summary>
        internal static string L_Grupos {
            get {
                return ResourceManager.GetString("L_Grupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardado correctamente.
        /// </summary>
        internal static string L_GuardadoCorrectamente {
            get {
                return ResourceManager.GetString("L_GuardadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string L_Guardar {
            get {
                return ResourceManager.GetString("L_Guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instalación individualizada.
        /// </summary>
        internal static string L_InstalacionIndividualizada {
            get {
                return ResourceManager.GetString("L_InstalacionIndividualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instalar.
        /// </summary>
        internal static string L_Instalar {
            get {
                return ResourceManager.GetString("L_Instalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instalar Escandallos.
        /// </summary>
        internal static string L_InstalarEscandallos {
            get {
                return ResourceManager.GetString("L_InstalarEscandallos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel 1 Materiales Base y Opciones.
        /// </summary>
        internal static string L_Level1MBOpciones {
            get {
                return ResourceManager.GetString("L_Level1MBOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Materiales Base ficticios.
        /// </summary>
        internal static string L_MBFicticios {
            get {
                return ResourceManager.GetString("L_MBFicticios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú.
        /// </summary>
        internal static string L_Menu {
            get {
                return ResourceManager.GetString("L_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú de opciones.
        /// </summary>
        internal static string L_MenuConfigurarOpciones {
            get {
                return ResourceManager.GetString("L_MenuConfigurarOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string L_Nombre {
            get {
                return ResourceManager.GetString("L_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron scripts .sql en la carpeta seleccionada..
        /// </summary>
        internal static string L_NoScriptsSql {
            get {
                return ResourceManager.GetString("L_NoScriptsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oculta en árbol.
        /// </summary>
        internal static string L_OcultaArbol {
            get {
                return ResourceManager.GetString("L_OcultaArbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocultar en lista.
        /// </summary>
        internal static string L_OcultaList {
            get {
                return ResourceManager.GetString("L_OcultaList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OcultaOpciones.
        /// </summary>
        internal static string L_OcultaOpciones {
            get {
                return ResourceManager.GetString("L_OcultaOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor Oculto añadido correctamente..
        /// </summary>
        internal static string L_OcultoAgregado {
            get {
                return ResourceManager.GetString("L_OcultoAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        internal static string L_Opciones {
            get {
                return ResourceManager.GetString("L_Opciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permitir traducciones en Escandallos y Conector de Herraje.
        /// </summary>
        internal static string L_PermitirTraduccion {
            get {
                return ResourceManager.GetString("L_PermitirTraduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalización clientes.
        /// </summary>
        internal static string L_PersonalizacionClientes {
            get {
                return ResourceManager.GetString("L_PersonalizacionClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presupuestado.
        /// </summary>
        internal static string L_Presupuestado {
            get {
                return ResourceManager.GetString("L_Presupuestado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Producción.
        /// </summary>
        internal static string L_Produccion {
            get {
                return ResourceManager.GetString("L_Produccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor(.
        /// </summary>
        internal static string L_Proveedor {
            get {
                return ResourceManager.GetString("L_Proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor Roto Frank SA agregado correctamente..
        /// </summary>
        internal static string L_ProveedorAgregado {
            get {
                return ResourceManager.GetString("L_ProveedorAgregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a registros actualizados.
        /// </summary>
        internal static string L_RegistrosActualizados {
            get {
                return ResourceManager.GetString("L_RegistrosActualizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a registros afectados para el script.
        /// </summary>
        internal static string L_RegistrosActualizadosScript {
            get {
                return ResourceManager.GetString("L_RegistrosActualizadosScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restaurar opciones.
        /// </summary>
        internal static string L_RestaurarOpciones {
            get {
                return ResourceManager.GetString("L_RestaurarOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scripts ejecutados correctamente..
        /// </summary>
        internal static string L_ScriptsEjecutados {
            get {
                return ResourceManager.GetString("L_ScriptsEjecutados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar manualmente los escandallos.
        /// </summary>
        internal static string L_SeleccionarEscandallos {
            get {
                return ResourceManager.GetString("L_SeleccionarEscandallos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar idioma.
        /// </summary>
        internal static string L_SeleccionarIdioma {
            get {
                return ResourceManager.GetString("L_SeleccionarIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar todos.
        /// </summary>
        internal static string L_SeleccionarTodos {
            get {
                return ResourceManager.GetString("L_SeleccionarTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar todos los grupos.
        /// </summary>
        internal static string L_SeleccionarTodosGrupos {
            get {
                return ResourceManager.GetString("L_SeleccionarTodosGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto.
        /// </summary>
        internal static string L_Texto {
            get {
                return ResourceManager.GetString("L_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Traducción.
        /// </summary>
        internal static string L_Traduccion {
            get {
                return ResourceManager.GetString("L_Traduccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        internal static string L_Valor {
            get {
                return ResourceManager.GetString("L_Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Escandallos.
        /// </summary>
        internal static string L_VerEscandallos {
            get {
                return ResourceManager.GetString("L_VerEscandallos", resourceCulture);
            }
        }
    }
}
